services:
  admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@enarmapi.com"
      PGADMIN_DEFAULT_PASSWORD: "test"
      SCRIPT_NAME: "/pgadmin4"
    ports:
      - "8080:80"

  database:
    image: postgres:14
    volumes:
      - db_pg_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-init.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: database
      DATABASE_USER: postgres
      DATABASE_PASSWORD: test
      DATABASE_NAME: enarm_development
      RAILS_ENV: development
    depends_on:
      - database
    stdin_open: true
    tty: true
volumes:
  db_pg_data: {}  
