FROM ruby:3.2.0-slim

WORKDIR /app

RUN apt-get update -qq && apt-get install -y build-essential nodejs
RUN apt-get install -y postgresql postgresql-contrib libpq-dev curl

ENV BUNDLE_PATH=/gems \
    RAILS_ENV=development

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v 2.4.5    
RUN bundle check || bundle install

COPY . ./

EXPOSE 3000

CMD ["bundle","exec","rails", "server", "-b", "0.0.0.0"]
